name: version-check
description: Check version if updated or not

runs:
  using: composite
  steps:
    - name: Publish files # this has the files of this repo
      uses: actions/upload-artifact@v3
      with:
        name: version-check-script
        path: version-check/version-check.py
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 2
    - run: |
        echo "This current path is $(pwd)"
        echo "Files under the current directory are:"
        ls
      shell: bash
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: version-check-script
      run: |
        ls -R
    - run: |
        if [ -f project.toml ]; then
          cat project.toml
        else
          echo "project.toml file not exists! Check your project setup!"
          exit 1
        fi
      shell: bash
    - name: Git log
      run: |
        echo "Current branch is: "
        git branch -vv

        echo "Git log hisotry are: "
        git log

      shell: bash
    - run: |
        git log -p HEAD^..HEAD -- project.toml | grep version || \

        if [ $? != 0 ]; then
          echo "No version being updated! Check before merge!"
          exit 1
        else
          echo "Version has been updated, can merge safely"
          exit 0
        fi
      shell: bash