name: version-check
description: Check version if updated or not

runs:
  using: composite
  steps:
    - run: |
        pwd
        ls
      shell: bash
    - run: |
        git log -p HEAD^..HEAD -- project.toml | grep version || \

        if [ $? != 0 ]; then
          echo "No version being updated! Check before merge!"
          exit 1
        else
          echo "Version has been updated, can merge safely"
          exit 0
        fi
      shell: bash