name: version-check
description: Check version if updated or not

runs:
  using: composite
  steps:
    - run:
        ls 
        chmod +x version-check.sh
        ./version-check.sh
      shell:  bash
