name: Tags Test Workflow
on:
  pull_request:

jobs:
  tag_check_test:
    runs-on: ubuntu-latest
    name: Tag Check Action Testing
    steps:
      - uses: actions/checkout@v3
      - uses: LonelyPorter/porter-actions/git-tags@action-tag

