name: Version Actions Test Workflow
on: [push]

jobs:
  version_check_test:
    runs-on: ubuntu-latest
    name: Version Check Action Testing
    steps:
      - uses: actions/checkout@v3
        # with:
        #   ref: ${{ github.event.pull_request.head.sha }}
        #   fetch-depth: 2
      - uses: LonelyPorter/porter-actions/version-check@version

