name: Version Actions Test Workflow
on: [push]

jobs:
  version_check_test:
    runs-on: ubuntu-latest
    name: Version Check Action Testing
    steps:
      - uses: LonelyPorter/porter-actions/version-check@version

